declare module "*.tf" { const content: string; export default content; }
declare module "*.yml" { const content: string; export default content; }
declare module "*.yaml" { const content: string; export default content; }
declare module "*.cfg" { const content: string; export default content; }
declare module "*.ini" { const content: string; export default content; }
declare module "*.env" { const content: string; export default content; }
declare module "*.sh" { const content: string; export default content; }
declare module "*/Caddyfile" { const content: string; export default content; }
declare module "*/authorized-keys" { const content: string; export default content; }
declare module "*/deploy" { const content: string; export default content; }
declare module "*/once" { const content: string; export default content; }
declare module "*/backup" { const content: string; export default content; }
