import {orchestrate,plan_deployment,read_deployment,source_cidrs,validate_deployment,backend_plan} from 'colors-compute-red';
import type {Opts} from 'red/workflow';
import {mkdirSync,writeFileSync} from 'node:fs';
import {join} from 'node:path';
export const topology=[{role:null,count:1}];
export function requirements(opts:Opts){const ssh=source_cidrs(opts,'ssh-sources','umami-ssh-sources'),http=source_cidrs(opts,'http-sources','umami-http-sources');return {single_host:true,legacy_state_keys:[opts.profile+'/umami-infrastructure.tfstate'],security:{ingress:[{id:'ssh',protocol:'tcp',from_port:22,to_port:22,sources:ssh},...http.length?[80,443].map(port=>({id:'http-'+port,protocol:'tcp',from_port:port,to_port:port,sources:http})):[]],egress:'all',private_filter:false}};}
export function errors(opts:Opts){try{validate_deployment(opts,topology,requirements(opts));backend_plan(opts,opts.profile+'/compute/shared.tfstate');return [];}catch{return ['invalid compute deployment requirements'];}}
export const planned=(opts:Opts)=>plan_deployment(opts,topology,requirements(opts));
export function node(result:any){const nodes=result.cluster?.nodes??[];if(nodes.length!==1||!nodes[0].ip)throw Error('compute node unavailable');return nodes[0];}
export function attach(opts:Opts,result:any):Opts{if(!['planned','ready','present','destroyed'].includes(result.status))return {...opts,'red/exit':1,'red/err':result.errors?.join('\n')||'compute lifecycle refused'};if(result.status==='destroyed')return {...opts,'red/exit':0,'umami/already-destroyed':true};let path=result.key?.private_key_path;if(path&&(opts['red/event']==='build'||opts['red/dry-run']))path=path.replace('$HOME','/home/build-placeholder');return {...opts,...node(result),'colors-compute/cluster':result.cluster,'red/exit':0,...path?{'ssh-private-key-path':path}:{}};}
export async function infrastructureStep(opts:Opts):Promise<Opts>{try{const planning=opts['red/event']==='build'||opts['red/dry-run'];const result:any=planning?planned(opts):await orchestrate(opts,topology,requirements(opts));if(planning){const root=join(opts.workdir,opts.profile,'compute'),stages:any={shared:result.documents.shared,...Object.fromEntries(Object.entries(result.documents.nodes).map(([key,docs])=>['nodes/'+key,docs]))};const sorted=(v:any):any=>Array.isArray(v)?v.map(sorted):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,sorted(v[k])])):v;for(const [stage,documents] of Object.entries(stages)){mkdirSync(join(root,stage),{recursive:true});for(const [name,doc] of Object.entries({...documents as any, "backend.tf.json":backend_plan(opts,stage==="shared"?result.state_keys.shared:result.state_keys.nodes[stage.slice(6)]).config}))writeFileSync(join(root,stage,name),JSON.stringify(sorted(doc),null,2)+'\n');}}return attach(opts,result);}catch{return {...opts,'red/exit':1,'red/err':'invalid compute deployment requirements'};}}
export async function load(opts:Opts,env?:Record<string,string|undefined>){return attach(opts,await read_deployment(opts,env,undefined,requirements(opts)));}
